### PR TITLE
Remove jquery

### LINKED ISSUE #2: JQUERY IS TRASH!!! OMG 2021 JQUERY BROO WHYYY SMH SMH SMH
COME AT ME BRO

### PR DESCRIPTION
**Pull request by Pustur**
Closes #2 😄

### CODE REVIEW

**Comment by LedAndris** [comment]
I probably hate jquery more then u do, but native js had issues with indexing so I just moved it to jquery

**Comment by Pustur** [comment]
I have never heard of indexing issues due to using/not using jQuery... You mean you didn't rank as high as you wanted to in google or other search engines? That would be very weird.

Anyway, I don't hate jQuery, I just like to remove it from projects that don't really need it :)

Feel free to close this if you don't want to merge it.

**Comment by LedAndris** [comment]
I dont have closing perms, nor I want to close it, the issue was: I queried the classes with `document.querySelectorAll` then when I wanted to index that object in both ways (`elems[idx]` or `elems.item(idx)`) it returned null for some reason, but when I printed the object all elements were in it. So I had no clue what I fucked up so I just ended up using jquery.

**Review by LedAndris — APPROVED** [review]
I tested it and it works, feel free to merge  noods @goodnightnoodles

**Comment by Pustur** [comment]
Ah ok, I thought you meant indexing as in SEO problems. Now it makes sense, thanks for merging.

**Comment by LedAndris** [comment]
this is a joke page for dissing one of our friend so SEO doesnt really matter

**Pull request merged**
